name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isocalendar 3D
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Joaquim-Salles
          template: classic
          base: ""
          config_timezone: America/Bahia
          config_padding: 0, 8px
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
